// Comprehensive Afghan Recipes Database
const afghanRecipes = [
    {
        id: 1,
        name: "Kabuli Pulao",
        category: "rice",
        description: "Afghanistan's national dish - aromatic rice with tender lamb, carrots, and raisins",
        prepTime: "30 min",
        cookTime: "90 min",
        servings: 6,
        difficulty: "Medium",
        ingredients: [
            "2 lbs lamb or beef, cut into chunks",
            "3 cups basmati rice",
            "2 large onions, sliced",
            "2 large carrots, julienned",
            "1/2 cup raisins",
            "1/2 cup almonds, sliced",
            "4 cloves garlic, minced",
            "2 tsp cumin seeds",
            "1 tsp cardamom pods",
            "1 cinnamon stick",
            "1 tsp turmeric",
            "Salt and pepper to taste",
            "4 tbsp vegetable oil",
            "Fresh cilantro for garnish"
        ],
        instructions: [
            "Soak basmati rice in water for 30 minutes, then drain.",
            "Heat oil in a large pot and brown the meat on all sides.",
            "Add onions and cook until golden brown.",
            "Add garlic, cumin, cardamom, cinnamon, and turmeric. Cook for 2 minutes.",
            "Add enough water to cover meat, bring to boil, then simmer for 45 minutes.",
            "In a separate pan, sauté carrots until tender and caramelize with a bit of sugar.",
            "Fry almonds until golden and set aside.",
            "Add rice to the meat pot with salt. Add water if needed.",
            "Bring to boil, then reduce heat and simmer covered for 20 minutes.",
            "Layer carrots, raisins, and almonds on top of rice.",
            "Cover and let rest for 10 minutes before serving.",
            "Garnish with fresh cilantro and serve hot."
        ],
        icon: "🍚"
    },
    {
        id: 2,
        name: "Mantu",
        category: "meat",
        description: "Steamed dumplings filled with spiced ground meat, served with yogurt and tomato sauce",
        prepTime: "60 min",
        cookTime: "45 min",
        servings: 4,
        difficulty: "Hard",
        ingredients: [
            "2 cups all-purpose flour",
            "1/2 cup warm water",
            "1 tsp salt",
            "1 lb ground beef or lamb",
            "2 medium onions, finely chopped",
            "3 cloves garlic, minced",
            "1 tsp ground coriander",
            "1/2 tsp ground cumin",
            "Salt and pepper to taste",
            "2 cups plain yogurt",
            "2 tbsp tomato paste",
            "2 tbsp vegetable oil",
            "Fresh mint leaves",
            "Red pepper flakes"
        ],
        instructions: [
            "Mix flour, water, and salt to make dough. Knead until smooth and let rest for 30 minutes.",
            "For filling, sauté onions until translucent, add garlic and spices.",
            "Add ground meat and cook until browned. Season with salt and pepper. Let cool.",
            "Roll dough very thin and cut into 4-inch squares.",
            "Place a spoonful of filling in center of each square.",
            "Fold corners together and pinch to seal, forming small pouches.",
            "Steam dumplings in a steamer for 30-40 minutes until cooked through.",
            "For sauce, mix tomato paste with a little water and heat.",
            "Serve mantu hot with yogurt, tomato sauce, and fresh mint.",
            "Sprinkle with red pepper flakes if desired."
        ],
        icon: "🥟"
    },
    {
        id: 3,
        name: "Ashak",
        category: "vegetables",
        description: "Leek-filled dumplings served with meat sauce and yogurt",
        prepTime: "90 min",
        cookTime: "60 min",
        servings: 6,
        difficulty: "Hard",
        ingredients: [
            "3 cups all-purpose flour",
            "1 cup warm water",
            "1 tsp salt",
            "4 large leeks, chopped fine",
            "1 bunch fresh cilantro, chopped",
            "1/2 lb ground beef",
            "1 large onion, diced",
            "3 cloves garlic, minced",
            "2 cups plain yogurt",
            "2 tbsp tomato paste",
            "1 tsp turmeric",
            "1/2 tsp red pepper flakes",
            "Salt and pepper to taste",
            "3 tbsp vegetable oil"
        ],
        instructions: [
            "Make dough with flour, water, and salt. Knead well and rest for 1 hour.",
            "Sauté leeks until soft, add cilantro and season. Let cool completely.",
            "Roll dough thin and cut into circles about 4 inches in diameter.",
            "Place leek filling in center and fold to make half-moon shapes.",
            "Boil dumplings in salted water for 15-20 minutes until they float.",
            "For meat sauce, brown ground beef with onions and garlic.",
            "Add tomato paste, turmeric, and spices. Simmer for 20 minutes.",
            "Mix yogurt with a little salt and garlic.",
            "Serve ashak topped with meat sauce and yogurt.",
            "Garnish with red pepper flakes and fresh herbs."
        ],
        icon: "🧄"
    },
    {
        id: 4,
        name: "Qorma Sabzi",
        category: "vegetables",
        description: "Herb stew with lamb and kidney beans, flavored with fresh herbs",
        prepTime: "20 min",
        cookTime: "120 min",
        servings: 6,
        difficulty: "Medium",
        ingredients: [
            "2 lbs lamb or beef, cubed",
            "1 cup kidney beans, soaked overnight",
            "2 bunches spinach, chopped",
            "1 bunch cilantro, chopped",
            "1 bunch parsley, chopped",
            "1 bunch green onions, chopped",
            "2 large onions, sliced",
            "4 cloves garlic, minced",
            "2 tsp turmeric",
            "1 tsp ground coriander",
            "1 dried lime (limu omani)",
            "Salt and pepper to taste",
            "4 tbsp vegetable oil"
        ],
        instructions: [
            "Heat oil in a large pot and brown meat on all sides.",
            "Add onions and cook until golden.",
            "Add garlic, turmeric, and coriander. Cook for 2 minutes.",
            "Add enough water to cover meat and bring to boil.",
            "Add soaked kidney beans and dried lime.",
            "Simmer covered for 1.5 hours until meat is tender.",
            "Add all chopped herbs and mix well.",
            "Continue cooking for 30 minutes until herbs are wilted.",
            "Season with salt and pepper to taste.",
            "Serve hot with basmati rice or Afghan bread."
        ],
        icon: "🌿"
    },
    {
        id: 5,
        name: "Bolani",
        category: "bread",
        description: "Stuffed flatbread with potatoes, leeks, or pumpkin",
        prepTime: "45 min",
        cookTime: "30 min",
        servings: 8,
        difficulty: "Medium",
        ingredients: [
            "3 cups all-purpose flour",
            "1 cup warm water",
            "1 tsp salt",
            "2 tbsp vegetable oil",
            "3 large potatoes, boiled and mashed",
            "2 leeks, finely chopped",
            "1/2 cup fresh cilantro, chopped",
            "1 tsp ground coriander",
            "1/2 tsp red pepper flakes",
            "Salt and pepper to taste",
            "Oil for frying"
        ],
        instructions: [
            "Mix flour, water, salt, and oil to make a soft dough. Rest for 30 minutes.",
            "For filling, mix mashed potatoes with sautéed leeks and cilantro.",
            "Season filling with coriander, red pepper flakes, salt, and pepper.",
            "Divide dough into 8 portions and roll each very thin.",
            "Spread filling on half of each circle, leaving edges clear.",
            "Fold dough over filling and seal edges by pressing with fork.",
            "Heat oil in a large skillet over medium heat.",
            "Fry bolani on both sides until golden and crispy.",
            "Drain on paper towels and serve hot.",
            "Traditionally served with yogurt or chutney."
        ],
        icon: "🫓"
    },
    {
        id: 6,
        name: "Sheer Khurma",
        category: "desserts",
        description: "Sweet milk pudding with vermicelli, dates, and nuts",
        prepTime: "15 min",
        cookTime: "45 min",
        servings: 6,
        difficulty: "Easy",
        ingredients: [
            "4 cups whole milk",
            "1/2 cup vermicelli, broken into pieces",
            "1/2 cup sugar",
            "1/4 cup dates, pitted and chopped",
            "1/4 cup almonds, sliced",
            "1/4 cup pistachios, chopped",
            "2 tbsp ghee or butter",
            "4-5 cardamom pods, crushed",
            "1/4 tsp rose water (optional)",
            "Coconut flakes for garnish"
        ],
        instructions: [
            "Heat ghee in a heavy-bottomed pan and roast vermicelli until golden.",
            "Add milk to the pan and bring to a gentle boil.",
            "Add cardamom pods and simmer for 15 minutes, stirring occasionally.",
            "Add sugar and dates, continue cooking for 10 minutes.",
            "Add half of the nuts and cook for another 10 minutes.",
            "The mixture should thicken to a pudding consistency.",
            "Add rose water if using and mix gently.",
            "Serve warm or chilled, garnished with remaining nuts and coconut.",
            "This dessert is traditionally served during Eid celebrations."
        ],
        icon: "🍮"
    },
    {
        id: 7,
        name: "Afghan Green Tea",
        category: "drinks",
        description: "Traditional green tea with cardamom and sugar",
        prepTime: "5 min",
        cookTime: "10 min",
        servings: 4,
        difficulty: "Easy",
        ingredients: [
            "4 cups water",
            "3 tbsp green tea leaves",
            "6-8 cardamom pods, lightly crushed",
            "Sugar to taste",
            "Fresh mint leaves (optional)"
        ],
        instructions: [
            "Bring water to a boil in a medium saucepan.",
            "Add cardamom pods and boil for 2 minutes.",
            "Add green tea leaves and reduce heat to low.",
            "Simmer for 5-7 minutes until tea is fragrant.",
            "Strain tea into a teapot or serving cups.",
            "Add sugar to taste and stir well.",
            "Garnish with fresh mint leaves if desired.",
            "Serve hot in small glasses or cups.",
            "Traditionally accompanied by sweets or nuts."
        ],
        icon: "🫖"
    },
    {
        id: 8,
        name: "Kofta Chalao",
        category: "meat",
        description: "Spiced meatballs in tomato sauce served with white rice",
        prepTime: "30 min",
        cookTime: "60 min",
        servings: 6,
        difficulty: "Medium",
        ingredients: [
            "2 lbs ground beef or lamb",
            "1 large onion, finely chopped",
            "4 cloves garlic, minced",
            "1 egg",
            "1/2 cup breadcrumbs",
            "2 tsp ground coriander",
            "1 tsp ground cumin",
            "1/2 tsp cinnamon",
            "3 large tomatoes, chopped",
            "2 tbsp tomato paste",
            "2 cups basmati rice",
            "Salt and pepper to taste",
            "3 tbsp vegetable oil",
            "Fresh cilantro for garnish"
        ],
        instructions: [
            "Mix ground meat with half the onion, garlic, egg, breadcrumbs, and spices.",
            "Form mixture into walnut-sized meatballs.",
            "Heat oil in a large pan and brown meatballs on all sides.",
            "Remove meatballs and set aside.",
            "Sauté remaining onions until golden, add tomatoes and tomato paste.",
            "Cook sauce for 15 minutes until thickened.",
            "Return meatballs to sauce and simmer covered for 30 minutes.",
            "Meanwhile, cook rice according to package directions.",
            "Serve kofta over rice, garnished with fresh cilantro.",
            "Accompany with Afghan bread and yogurt."
        ],
        icon: "🍖"
    },
    {
        id: 9,
        name: "Aushak",
        category: "vegetables",
        description: "Scallion dumplings with yogurt and meat sauce",
        prepTime: "120 min",
        cookTime: "45 min",
        servings: 6,
        difficulty: "Hard",
        ingredients: [
            "3 cups flour",
            "1 cup warm water",
            "1 tsp salt",
            "4 bunches scallions, chopped",
            "1/2 lb ground beef",
            "2 cups plain yogurt",
            "2 cloves garlic, minced",
            "2 tbsp tomato paste",
            "1 tsp turmeric",
            "1/2 tsp red pepper flakes",
            "Fresh mint, chopped",
            "Salt and pepper to taste",
            "Oil for cooking"
        ],
        instructions: [
            "Make dough with flour, water, and salt. Knead and rest for 1 hour.",
            "Sauté scallions until wilted, season with salt and pepper. Cool.",
            "Roll dough very thin and cut into 3-inch squares.",
            "Place scallion filling in center and fold into triangles.",
            "Boil dumplings in salted water until they float.",
            "Brown ground beef with garlic, add tomato paste and turmeric.",
            "Simmer meat sauce for 20 minutes.",
            "Mix yogurt with minced garlic and salt.",
            "Serve aushak with meat sauce and garlic yogurt.",
            "Garnish with fresh mint and red pepper flakes."
        ],
        icon: "🧅"
    },
    {
        id: 10,
        name: "Naan-e Afghan",
        category: "bread",
        description: "Traditional Afghan flatbread baked in tandoor or oven",
        prepTime: "120 min",
        cookTime: "20 min",
        servings: 8,
        difficulty: "Medium",
        ingredients: [
            "4 cups bread flour",
            "1 cup warm water",
            "2 tbsp plain yogurt",
            "2 tsp active dry yeast",
            "1 tsp sugar",
            "1 tsp salt",
            "2 tbsp vegetable oil",
            "Nigella seeds (kalonji) for topping",
            "Sesame seeds for topping"
        ],
        instructions: [
            "Dissolve yeast and sugar in warm water. Let stand for 5 minutes.",
            "Mix flour and salt in a large bowl.",
            "Add yeast mixture, yogurt, and oil to flour.",
            "Knead dough until smooth and elastic, about 10 minutes.",
            "Place in oiled bowl, cover, and rise for 1.5 hours.",
            "Divide dough into 8 portions and shape into ovals.",
            "Let rest for 30 minutes covered.",
            "Preheat oven to 500°F with pizza stone if available.",
            "Stretch dough and sprinkle with seeds.",
            "Bake for 8-10 minutes until puffed and golden.",
            "Serve warm with meals or use for wrapping kebabs."
        ],
        icon: "🍞"
    },
    {
        id: 11,
        name: "Firni",
        category: "desserts",
        description: "Creamy rice pudding flavored with cardamom and rose water",
        prepTime: "10 min",
        cookTime: "45 min",
        servings: 6,
        difficulty: "Easy",
        ingredients: [
            "4 cups whole milk",
            "1/3 cup rice flour",
            "1/2 cup sugar",
            "1/2 tsp ground cardamom",
            "1 tsp rose water",
            "1/4 cup pistachios, chopped",
            "1/4 cup almonds, sliced",
            "Silver leaf (varq) for decoration (optional)"
        ],
        instructions: [
            "Mix rice flour with 1/2 cup milk to make smooth paste.",
            "Heat remaining milk in heavy-bottomed pan over medium heat.",
            "When milk starts to boil, slowly add rice flour paste while stirring.",
            "Cook on low heat, stirring constantly, for 30-35 minutes.",
            "Add sugar and cardamom, continue cooking for 10 minutes.",
            "Mixture should coat the back of a spoon when ready.",
            "Remove from heat and add rose water.",
            "Pour into individual serving bowls.",
            "Refrigerate for at least 2 hours before serving.",
            "Garnish with nuts and silver leaf if using."
        ],
        icon: "🥛"
    },
    {
        id: 12,
        name: "Doogh",
        category: "drinks",
        description: "Refreshing yogurt drink with mint and cucumber",
        prepTime: "10 min",
        cookTime: "0 min",
        servings: 4,
        difficulty: "Easy",
        ingredients: [
            "2 cups plain yogurt",
            "1 cup cold water",
            "1/2 cucumber, grated",
            "2 tbsp fresh mint, chopped",
            "1 tsp salt",
            "1/2 tsp dried mint",
            "Ice cubes",
            "Fresh mint sprigs for garnish"
        ],
        instructions: [
            "Whisk yogurt until smooth in a large bowl.",
            "Gradually add cold water while whisking.",
            "Add grated cucumber, fresh mint, and salt.",
            "Mix well and chill for at least 1 hour.",
            "Taste and adjust salt if needed.",
            "Serve over ice in tall glasses.",
            "Garnish with fresh mint sprigs and dried mint.",
            "Stir before serving as ingredients may separate.",
            "Perfect accompaniment to spicy Afghan dishes."
        ],
        icon: "🥤"
    }
];

// Export for use in main script
if (typeof module !== 'undefined' && module.exports) {
    module.exports = afghanRecipes;
}